#!/usr/bin/python3

from sys import argv

if len(argv) != 2:
    print("Usage: factors <file>")

with open(argv[1], mode="r", encoding="utf-8") as f:
    for line in f:
        q = 2
        n = int(line)
        while q <= n:
            if n % q == 0:
                p = n // q
                print("{}={}*{}".format(n, p, q))
                break
            q += 1
