#!/usr/bin/python3

from sys import argv
from math import sqrt

if len(argv) != 2:
    print("Usage: factors <file>")

with open(argv[1], mode="r") as f:
    for line in f:
        n = int(line)
        flag = 0
        if n % 2 == 0:
            print("{}={}*{}".format(n, n // 2, 2))
            flag = 1
        else:
            q = 3
            for q in range(3, int(sqrt(n)) + 1, 2):
                if n % q == 0:
                    p = n // q
                    print("{}={}*{}".format(n, p, q))
                    flag = 1
                    break
        if flag == 0:
            print("{}={}*{}".format(n, n, 1))
